#!/usr/bin/env bash
NVIM_ADDR="${NVIM_SOCKET_PATH:-$NVIM}"
[[ -z "$NVIM_ADDR" ]] && exit 0
[[ -z "$1" ]] && exit 1
SELF="$0"
[[ -L "$SELF" ]] && SELF="$(readlink "$SELF")"
NR="$(cd "$(dirname "$SELF")" && pwd)/nvim-remote"
win=$("$NR/nvim-lua" "return require('sodium.utils').editor_window()")
[[ -z "$win" ]] && exit 0
"$NR/nvim-open" --window "$win" "$1"